name: chatbot_bksi
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - langchain
    - langchain-core
    - langchain-community
    - langchain-chroma
    - langchain-text-splitters
    - sentence-transformers
    - chromadb
    - gradio
    - streamlit
    - python-dotenv
